import Head from "next/head";
import Navigatebar from "../components/Navigatebar.js";
import React from "react";
import Script from "next/script.js";
import {LogoutButton} from "@/components/dashboard-test-logout/professional-dashboard.js"


export default function Login() {
  
  

  return (
    <>
       <Head key={Math.random()}>
          <title>Get That Job</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <Script src="https://cdn.tailwindcss.com"/>
        </Head>
      <Navigatebar />
        <div className="mb-[32px]">
          <h3 className="mt-[32px] mb-[16px] max-[767px]:text-center text-left" id="heading3">Welcome Back</h3>
          <h6 className="max-[767px]:text-center text-left font-medium tracking-[.15px] " id="subtitle1">professional</h6>
        </div>
      <LogoutButton/>

    </>
  );
}
