import Head from "next/head";
import Contentsection from "../components/Contentsection.js";
import Navigatebar from "../components/Navigatebar.js";
import Headers from "@/components/Headers.js";
import Footer from "@/components/Footer.js";

export default function Home() {
  return (
    <>
      <Head key={Math.random()}>
        <title>Get That Job</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      <Navigatebar />
      <Headers />
      <Contentsection />
      <Footer />
    </>
  );
}

//Best JPG = Background ma
//Best PNG = Background no ma
