import Head from "next/head";
import Navigatebar from "../components/Navigatebar.js";
import { ProfessionalLogin } from "@/components/login-page/ProfessionalLogin.js";
import { RecruiterLogin } from "@/components/login-page/RecruiterLogin.js";
import BackgroundMan from "../components/BackgroundMan.js";
import React, { useState } from "react";

export default function Login() {
  const [activeTab, setActiveTab] = useState("regular");

  const handleClick = (tab) => {
    if (tab !== activeTab) {
      // เพิ่มเงื่อนไขในการใช้ setActiveTab
      setActiveTab(tab);
    }
  };

  return (
    <>
      <Head key={Math.random()}>
        <title>Get That Job</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigatebar />
      <BackgroundMan>
        <div className="mb-[32px]">
          <h3
            className="mt-[32px] mb-[16px] max-[767px]:text-center text-left"
            id="heading3"
          >
            Welcome Back
          </h3>
          <h6
            className="max-[767px]:text-center text-left font-medium tracking-[.15px] "
            id="subtitle1"
          >
            Login to you account as...
          </h6>
        </div>
        <div className="flex max-[767px]:justify-center justify-start space-x-4 mb-1">
          <button
            className={`border-b-4 border-[#BDBDBD] hover:border-b-[#F48FB1] ${
              activeTab === "regular"
                ? "border-b-[#F48FB1]"
                : "border-[#BDBDBD]"
            }`}
            onClick={() => handleClick("regular")}
          >
            <p id="body2 mb-[6px]">PROFESSIONAL</p>
          </button>
          <button
            className={`border-b-4 border-[#BDBDBD] hover:border-b-[#F48FB1] ${
              activeTab === "recruiter"
                ? "border-b-[#F48FB1]"
                : "border-[#BDBDBD]"
            }`}
            onClick={() => handleClick("recruiter")}
          >
            <p id="body2  mb-[6px]">RECRUITER</p>
          </button>
        </div>
        {activeTab === "regular" ? <ProfessionalLogin /> : <RecruiterLogin />}
      </BackgroundMan>
    </>
  );
}
