import Head from "next/head";
import { Inter } from "next/font/google";
import Navigatebar from "../components/Navigatebar.js";
import Registerform from "../components/register-page/Registerform.js"


export default function Register() {
    return (
      <>
        <Head key={Math.random()}>
          <title>Get That Job</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <script src="https://cdn.tailwindcss.com"></script>
        </Head>
  
        <Navigatebar />
        <Registerform />
        
      </>
    );
  }